# --- General Settings ---
bind 0.0.0.0
port 6379
appendonly yes
protected-mode no


# ---- Persistence: RDB (Snapshots) -------
# Save the DB on disk:
# after 900 sec (15 min) if at least 1 key changed
# after 300 sec (5 min) if at least 10 keys changed
# after 60 sec if at least 10000 keys changed
save 900 1
save 300 10
save 60 10000


# --- Persistence: AOF (Append Only File) ---
appendonly yes
appendfilename "appendonly.aof"
# fsync every second (balance between performance and data safety)
appendfsync everysec


# Security (Optional but recommended)
# requirepass your_strong_password
# masterauth your_strong_password

# Strategy: Keep at least 1 replica synced before allowing writes
# (Prevents data loss during network partitions)
# min-replicas-to-write 1
# min-replicas-max-lag 10