# Network
bind 0.0.0.0 # [inside docker, can use (service name)]
port 6379


# Connection to master
# Syntax: replicaof <master-ip/hostname> <port>
replicaof redis-master 6379

# Replication settings
replica-read-only yes

# Persistence (Helps with fast restarts)
appendonly yes


# Security
# If master has a password, uncomment below:
# masterauth your_strong_password